services:
  - type: web
    name: superis
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        value: "SuperYes#admin"
      - key: DATA_DIR
        value: /data
      - key: PIXZY_TOKEN
        value: "662|E9ZcJF8XzHCHcvaFE4zR97AGYB13Sz2QrVOMbKBGaa48511d"
      - key: PUBLIC_URL
        value: https://atualizadoshojesim.onrender.com
      - key: TIKTOK_PIXEL_ID
        value: D38L3JBC77U1BQU6QEE0
      - key: TIKTOK_ACCESS_TOKEN
        value: 71c734458594233f9aaca0358b1e8a2af7ed7af3
      - key: PIX_GATEWAY
        value: flevopay
      - key: FLEVOPAY_STORE_ID
        value: "11099"
      - key: FLEVOPAY_SECRET
        value: flevopay_sk_ae9a299e6552ef2a2b0c7fc840e3fe1d400975d6b3fcf01f8ad5696735925823
