services:
  - type: web
    name: superis
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        value: SuperYes#admin
      - key: DATA_DIR
        value: /data
      - key: PIXZY_TOKEN
        value: ""
      - key: PUBLIC_URL
        value: ""
