services:
  - type: web
    name: superis
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /final/midia/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
